# Generated by Django 2.0 on 2018-04-11 20:59

import catalog.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=128)),
                ('import_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers')),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('maintainers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('kind', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('manual', 'manual'), ('other', 'other')], max_length=32)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('effect_file', models.FileField(upload_to=catalog.models.effect_version_filename)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Effect')),
            ],
        ),
    ]
