# Generated by Django 2.0 on 2018-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='kind',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('manual', 'manual'), ('other', 'other')], db_index=True, max_length=32),
        ),
    ]
