# Generated by Django 2.0 on 2018-04-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180411_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('effect', 'release_date')},
        ),
    ]
