# Generated by Django 2.0 on 2018-04-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180412_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='license',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
