# Generated by Django 2.0.4 on 2018-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_effect_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('pk',)},
        ),
    ]
